export enum CardIds {
  WRITING = 'WRITING',
  CLOTHING = 'CLOTHING',
  MASONRY = 'MASONRY',
  METALWORKING = 'METALWORKING',
  CODE_OF_LAWS = 'CODE_OF_LAWS',
  SAILING = 'SAILING',
  POTTERY = 'POTTERY',
  OARS = 'OARS',
  ARCHERY = 'ARCHERY',
  AGRICULTURE = 'AGRICULTURE',
  MYSTICISM = 'MYSTICISM',
  CITY_STATES = 'CITY_STATES',
  DOMESTICATION = 'DOMESTICATION',
  TOOLS = 'TOOLS',
  THE_WHEEL = 'THE_WHEEL',
  CURRENCY = 'CURRENCY',
  CANAL_BUILDING = 'CANAL_BUILDING',
  MONOTHEISM = 'MONOTHEISM',
  ROAD_BUILDING = 'ROAD_BUILDING',
  CONSTRUCTION = 'CONSTRUCTION',
  FERMENTING = 'FERMENTING',
  CALENDAR = 'CALENDAR',
  PHILOSOPHY = 'PHILOSOPHY',
  MATHEMATICS = 'MATHEMATICS',
  MAPMAKING = 'MAPMAKING',
  PAPER = 'PAPER',
  ENGINEERING = 'ENGINEERING',
  TRANSLATION = 'TRANSLATION',
  FEUDALISM = 'FEUDALISM',
  MACHINERY = 'MACHINERY',
  MEDICINE = 'MEDICINE',
  OPTICS = 'OPTICS',
  COMPASS = 'COMPASS',
  EDUCATION = 'EDUCATION',
  ALCHEMY = 'ALCHEMY',
  GUNPOWDER = 'GUNPOWDER',
  INVENTION = 'INVENTION',
  COLONIALISM = 'COLONIALISM',
  REFORMATION = 'REFORMATION',
  ANATOMY = 'ANATOMY',
  ENTERPRISE = 'ENTERPRISE',
  PERSPECTIVE = 'PERSPECTIVE',
  NAVIGATION = 'NAVIGATION',
  PRINTING_PRESS = 'PRINTING_PRESS',
  EXPERIMENTATION = 'EXPERIMENTATION',
  ASTRONOMY = 'ASTRONOMY',
  MEASUREMENT = 'MEASUREMENT',
  STATISTICS = 'STATISTICS',
  CHEMISTRY = 'CHEMISTRY',
  COAL = 'COAL',
  THE_PIRATE_CODE = 'THE_PIRATE_CODE',
  STEAM_ENGINE = 'STEAM_ENGINE',
  BANKING = 'BANKING',
  PHYSICS = 'PHYSICS',
  SOCIETIES = 'SOCIETIES',
  ATOMIC_THEORY = 'ATOMIC_THEORY',
  EMANCIPATION = 'EMANCIPATION',
  VACCINATION = 'VACCINATION',
  CLASSIFICATION = 'CLASSIFICATION',
  METRIC_SYSTEM = 'METRIC_SYSTEM',
  ENCYCLOPEDIA = 'ENCYCLOPEDIA',
  MACHINE_TOOLS = 'MACHINE_TOOLS',
  INDUSTRIALIZATION = 'INDUSTRIALIZATION',
  DEMOCRACY = 'DEMOCRACY',
  CANNING = 'CANNING',
  COMBUSTION = 'COMBUSTION',
  BICYCLE = 'BICYCLE',
  EVOLUTION = 'EVOLUTION',
  SANITATION = 'SANITATION',
  EXPLOSIVES = 'EXPLOSIVES',
  ELECTRICITY = 'ELECTRICITY',
  PUBLICATIONS = 'PUBLICATIONS',
  LIGHTING = 'LIGHTING',
  RAILROAD = 'RAILROAD',
  REFRIGERATION = 'REFRIGERATION',
  ANTIBIOTICS = 'ANTIBIOTICS',
  MOBILITY = 'MOBILITY',
  FLIGHT = 'FLIGHT',
  ROCKETRY = 'ROCKETRY',
  SKYSCRAPERS = 'SKYSCRAPERS',
  SOCIALISM = 'SOCIALISM',
  CORPORATIONS = 'CORPORATIONS',
  MASS_MEDIA = 'MASS_MEDIA',
  EMPIRICISM = 'EMPIRICISM',
  QUANTUM_THEORY = 'QUANTUM_THEORY',
  COMPUTERS = 'COMPUTERS',
  COLLABORATION = 'COLLABORATION',
  GENETICS = 'GENETICS',
  SERVICES = 'SERVICES',
  SPECIALIZATION = 'SPECIALIZATION',
  SUBURBIA = 'SUBURBIA',
  ECOLOGY = 'ECOLOGY',
  FISSION = 'FISSION',
  SATELLITES = 'SATELLITES',
  COMPOSITES = 'COMPOSITES',
  ROBOTICS = 'ROBOTICS',
  BIOENGINEERING = 'BIOENGINEERING',
  DATABASES = 'DATABASES',
  MINIATURIZATION = 'MINIATURIZATION',
  SOFTWARE = 'SOFTWARE',
  SELF_SERVICE = 'SELF_SERVICE',
  AI = 'AI',
  STEM_CELLS = 'STEM_CELLS',
  GLOBALIZATION = 'GLOBALIZATION',
  THE_INTERNET = 'THE_INTERNET',
}

export enum CardNames {
  WRITING = 'Writing',
  CLOTHING = 'Clothing',
  MASONRY = 'Masonry',
  METALWORKING = 'Metalworking',
  CODE_OF_LAWS = 'Code of Laws',
  SAILING = 'Sailing',
  POTTERY = 'Pottery',
  OARS = 'Oars',
  ARCHERY = 'Archery',
  AGRICULTURE = 'Agriculture',
  MYSTICISM = 'Mysticism',
  CITY_STATES = 'City States',
  DOMESTICATION = 'Domestication',
  TOOLS = 'Tools',
  THE_WHEEL = 'The Wheel',
  CURRENCY = 'Currency',
  CANAL_BUILDING = 'Canal Building',
  MONOTHEISM = 'Monotheism',
  ROAD_BUILDING = 'Road Building',
  CONSTRUCTION = 'Construction',
  FERMENTING = 'Fermenting',
  CALENDAR = 'Calendar',
  PHILOSOPHY = 'Philosophy',
  MATHEMATICS = 'Mathematics',
  MAPMAKING = 'Mapmaking',
  PAPER = 'Paper',
  ENGINEERING = 'Engineering',
  TRANSLATION = 'Translation',
  FEUDALISM = 'Feudalism',
  MACHINERY = 'Machinery',
  MEDICINE = 'Medicine',
  OPTICS = 'Optics',
  COMPASS = 'Compass',
  EDUCATION = 'Education',
  ALCHEMY = 'Alchemy',
  GUNPOWDER = 'Gunpowder',
  INVENTION = 'Invention',
  COLONIALISM = 'Colonialism',
  REFORMATION = 'Reformation',
  ANATOMY = 'Anatomy',
  ENTERPRISE = 'Enterprise',
  PERSPECTIVE = 'Perspective',
  NAVIGATION = 'Navigation',
  PRINTING_PRESS = 'Printing Press',
  EXPERIMENTATION = 'Experimentation',
  ASTRONOMY = 'Astronomy',
  MEASUREMENT = 'Measurement',
  STATISTICS = 'Statistics',
  CHEMISTRY = 'Chemistry',
  COAL = 'Coal',
  THE_PIRATE_CODE = 'The Pirate Code',
  STEAM_ENGINE = 'Steam Engine',
  BANKING = 'Banking',
  PHYSICS = 'Physics',
  SOCIETIES = 'Societies',
  ATOMIC_THEORY = 'Atomic Theory',
  EMANCIPATION = 'Emancipation',
  VACCINATION = 'Vaccination',
  CLASSIFICATION = 'Classification',
  METRIC_SYSTEM = 'Metric System',
  ENCYCLOPEDIA = 'Encyclopedia',
  MACHINE_TOOLS = 'Machine Tools',
  INDUSTRIALIZATION = 'Industrialization',
  DEMOCRACY = 'Democracy',
  CANNING = 'Canning',
  COMBUSTION = 'Combustion',
  BICYCLE = 'Bicycle',
  EVOLUTION = 'Evolution',
  SANITATION = 'Sanitation',
  EXPLOSIVES = 'Explosives',
  ELECTRICITY = 'Electricity',
  PUBLICATIONS = 'Publications',
  LIGHTING = 'Lighting',
  RAILROAD = 'Railroad',
  REFRIGERATION = 'Refrigeration',
  ANTIBIOTICS = 'Antibiotics',
  MOBILITY = 'Mobility',
  FLIGHT = 'Flight',
  ROCKETRY = 'Rocketry',
  SKYSCRAPERS = 'Skyscrapers',
  SOCIALISM = 'Socialism',
  CORPORATIONS = 'Corporations',
  MASS_MEDIA = 'Mass Media',
  EMPIRICISM = 'Empiricism',
  QUANTUM_THEORY = 'Quantum Theory',
  COMPUTERS = 'Computers',
  COLLABORATION = 'Collaboration',
  GENETICS = 'Genetics',
  SERVICES = 'Services',
  SPECIALIZATION = 'Specialization',
  SUBURBIA = 'Suburbia',
  ECOLOGY = 'Ecology',
  FISSION = 'Fission',
  SATELLITES = 'Satellites',
  COMPOSITES = 'Composites',
  ROBOTICS = 'Robotics',
  BIOENGINEERING = 'Bioengineering',
  DATABASES = 'Databases',
  MINIATURIZATION = 'Miniaturization',
  SOFTWARE = 'Software',
  SELF_SERVICE = 'Self Service',
  AI = 'A.I.',
  STEM_CELLS = 'Stem Cells',
  GLOBALIZATION = 'Globalization',
  THE_INTERNET = 'The Internet',
}

export enum Resources {
  CASTLES = 'castles',
  CROWNS = 'crowns',
  LEAVES = 'leaves',
  LIGHTBULBS = 'lightbulbs',
  FACTORIES = 'factories',
  TIMEPIECES = 'timepieces',
}

export enum SpecialAchievements {
  MONUMENT = 'Monument',
  EMPIRE = 'Empire',
  WORLD = 'World',
  WONDER = 'Wonder',
  UNIVERSE = 'Universe',
}

export enum Colors {
  RED = 'red',
  BLUE = 'blue',
  GREEN = 'green',
  PURPLE = 'purple',
  YELLOW = 'yellow',
}

export enum Ages {
  ONE = 1,
  TWO = 2,
  THREE = 3,
  FOUR = 4,
  FIVE = 5,
  SIX = 6,
  SEVEN = 7,
  EIGHT = 8,
  NINE = 9,
  TEN = 10,
}

export enum SplayDirections {
  LEFT = 'left',
  RIGHT = 'right',
  UP = 'up',
}

export const TOTAL_CARDS_IN_AGE = {
  [Ages.ONE]: 15,
  [Ages.TWO]: 10,
  [Ages.THREE]: 10,
  [Ages.FOUR]: 10,
  [Ages.FIVE]: 10,
  [Ages.SIX]: 10,
  [Ages.SEVEN]: 10,
  [Ages.EIGHT]: 10,
  [Ages.NINE]: 10,
  [Ages.TEN]: 10,
};

const BASE_AGE_ACHIEVEMENT = Object.freeze({
  card: undefined,
  cost: 0,
  isAvailable: true,
});

export const BASE_AGE_ACHIEVEMENTS = Object.freeze({
  [Ages.ONE]: { ...BASE_AGE_ACHIEVEMENT, cost: 5 },
  [Ages.TWO]: { ...BASE_AGE_ACHIEVEMENT, cost: 10 },
  [Ages.THREE]: { ...BASE_AGE_ACHIEVEMENT, cost: 15 },
  [Ages.FOUR]: { ...BASE_AGE_ACHIEVEMENT, cost: 20 },
  [Ages.FIVE]: { ...BASE_AGE_ACHIEVEMENT, cost: 25 },
  [Ages.SIX]: { ...BASE_AGE_ACHIEVEMENT, cost: 30 },
  [Ages.SEVEN]: { ...BASE_AGE_ACHIEVEMENT, cost: 35 },
  [Ages.EIGHT]: { ...BASE_AGE_ACHIEVEMENT, cost: 40 },
  [Ages.NINE]: { ...BASE_AGE_ACHIEVEMENT, cost: 45 },
  [Ages.TEN]: { ...BASE_AGE_ACHIEVEMENT, isAvailable: false },
});

export const BASE_SPECIAL_ACHIEVEMENTS = {
  [SpecialAchievements.EMPIRE]: true,
  [SpecialAchievements.MONUMENT]: true,
  [SpecialAchievements.WONDER]: true,
  [SpecialAchievements.WORLD]: true,
  [SpecialAchievements.UNIVERSE]: true,
};

export const AGE_NUMBER_TO_NAME = {
  [Ages.ONE]: 'PREHISTORY',
  [Ages.TWO]: 'CLASSICAL',
  [Ages.THREE]: 'MEDIEVAL',
  [Ages.FOUR]: 'RENAISSANCE',
  [Ages.FIVE]: 'EXPLORATION',
  [Ages.SIX]: 'ENLIGHTENMENT',
  [Ages.SEVEN]: 'ROMANCE',
  [Ages.EIGHT]: 'MODERN',
  [Ages.NINE]: 'POSTMODERN',
  [Ages.TEN]: 'INFORMATION',
};
