export enum Cards {
  WRITING = 'Writing',
  CLOTHING = 'Clothing',
  MASONRY = 'Masonry',
  METALWORKING = 'Metalworking',
  CODE_OF_LAWS = 'Code of Laws',
  SAILING = 'Sailing',
  POTTERY = 'Pottery',
  OARS = 'Oars',
  ARCHERY = 'Archery',
  AGRICULTURE = 'Agriculture',
  MYSTICISM = 'Mysticism',
  CITY_STATES = 'City States',
  DOMESTICATION = 'Domestication',
  TOOLS = 'Tools',
  THE_WHEEL = 'The Wheel',
  CURRENCY = 'Currency',
  CANAL_BUILDING = 'Canal Building',
  MONOTHEISM = 'Monotheism',
  ROAD_BUILDING = 'Road Building',
  CONSTRUCTION = 'Construction',
  FERMENTING = 'Fermenting',
  CALENDAR = 'Calendar',
  PHILOSOPHY = 'Philosophy',
  MATHEMATICS = 'Mathematics',
  MAPMAKING = 'Mapmaking',
  PAPER = 'Paper',
  ENGINEERING = 'Engineering',
  TRANSLATION = 'Translation',
  FEUDALISM = 'Feudalism',
  MACHINERY = 'Machinery',
  MEDICINE = 'Medicine',
  OPTICS = 'Optics',
  COMPASS = 'Compass',
  EDUCATION = 'Education',
  ALCHEMY = 'Alchemy',
  GUNPOWDER = 'Gunpowder',
  INVENTION = 'Invention',
  COLONIALISM = 'Colonialism',
  REFORMATION = 'Reformation',
  ANATOMY = 'Anatomy',
  ENTERPRISE = 'Enterprise',
  PERSPECTIVE = 'Perspective',
  NAVIGATION = 'Navigation',
  PRINTING_PRESS = 'Printing Press',
  EXPERIMENTATION = 'Experimentation',
  ASTRONOMY = 'Astronomy',
  MEASUREMENT = 'Measurement',
  STATISTICS = 'Statistics',
  CHEMISTRY = 'Chemistry',
  COAL = 'Coal',
  THE_PIRATE_CODE = 'The Pirate Code',
  STEAM_ENGINE = 'Steam Engine',
  BANKING = 'Banking',
  PHYSICS = 'Physics',
  SOCIETIES = 'Societies',
  ATOMIC_THEORY = 'Atomic Theory',
  EMANCIPATION = 'Emancipation',
  VACCINATION = 'Vaccination',
  CLASSIFICATION = 'Classification',
  METRIC_SYSTEM = 'Metric System',
  ENCYCLOPEDIA = 'Encyclopedia',
  MACHINE_TOOLS = 'Machine Tools',
  INDUSTRIALIZATION = 'Industrialization',
  DEMOCRACY = 'Democracy',
  CANNING = 'Canning',
  COMBUSTION = 'Combustion',
  BICYCLE = 'Bicycle',
  EVOLUTION = 'Evolution',
  SANITATION = 'Sanitation',
  EXPLOSIVES = 'Explosives',
  ELECTRICITY = 'Electricity',
  PUBLICATIONS = 'Publications',
  LIGHTING = 'Lighting',
  RAILROAD = 'Railroad',
  REFRIGERATION = 'Refrigeration',
  ANTIBIOTICS = 'Antibiotics',
  MOBILITY = 'Mobility',
  FLIGHT = 'Flight',
  ROCKETRY = 'Rocketry',
  SKYSCRAPERS = 'Skyscrapers',
  SOCIALISM = 'Socialism',
  CORPORATIONS = 'Corporations',
  MASS_MEDIA = 'Mass Media',
  EMPIRICISM = 'Empiricism',
  QUANTUM_THEORY = 'Quantum Theory',
  COMPUTERS = 'Computers',
  COLLABORATION = 'Collaboration',
  GENETICS = 'Genetics',
  SERVICES = 'Services',
  SPECIALIZATION = 'Specialization',
  SUBURBIA = 'Suburbia',
  ECOLOGY = 'Ecology',
  FISSION = 'Fission',
  SATELLITES = 'Satellites',
  COMPOSITES = 'Composites',
  ROBOTICS = 'Robotics',
  BIOENGINEERING = 'Bioengineering',
  DATABASES = 'Databases',
  MINIATURIZATION = 'Miniaturization',
  SOFTWARE = 'Software',
  SELF_SERVICE = 'Self Service',
  AI = 'A.I.',
  STEM_CELLS = 'Stem Cells',
  GLOBALIZATION = 'Globalization',
  THE_INTERNET = 'The Internet',
}

export enum Resources {
  CASTLES = 'castles',
  CROWNS = 'crowns',
  LEAVES = 'leaves',
  LIGHTBULBS = 'lightbulbs',
  FACTORIES = 'factories',
  TIMEPIECES = 'timepieces',
}

export enum SpecialAchievements {
  MONUMENT = 'Monument',
  EMPIRE = 'Empire',
  WORLD = 'World',
  WONDER = 'Wonder',
  UNIVERSE = 'Universe',
}

export enum Colors {
  RED = 'red',
  BLUE = 'blue',
  GREEN = 'green',
  PURPLE = 'purple',
  YELLOW = 'yellow',
}

export enum Ages {
  ONE = 1,
  TWO = 2,
  THREE = 3,
  FOUR = 4,
  FIVE = 5,
  SIX = 6,
  SEVEN = 7,
  EIGHT = 8,
  NINE = 9,
  TEN = 10,
}

export enum SplayDirections {
  LEFT = 'left',
  RIGHT = 'right',
  UP = 'up',
  DOWN = 'down',
}
